name: "✨ 功能请求"
description: 提出新功能或改进建议
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        感谢你的功能建议！请详细描述你的需求，帮助我们更好地理解和实现。

  - type: textarea
    id: summary
    attributes:
      label: "功能概述"
      description: 简要描述你希望添加的功能
      placeholder: 用一两句话描述这个功能...
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: "使用场景"
      description: 描述这个功能解决什么问题，或者在什么场景下使用
      placeholder: |
        作为一个用户，我希望...
        这样我就可以...
    validations:
      required: true

  - type: dropdown
    id: module
    attributes:
      label: "相关功能模块"
      description: 这个功能属于哪个模块？
      options:
        - 核心框架 (Bot Core)
        - 天气服务
        - 番剧服务
        - B站服务
        - LLM 对话
        - 定时推送
        - 新模块
        - 其他
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: "建议的解决方案"
      description: 如果你有具体的实现想法，请描述
      placeholder: 描述你认为应该如何实现这个功能...
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: "替代方案"
      description: 你考虑过的其他解决方案
      placeholder: 描述你考虑过的其他方案...
    validations:
      required: false

  - type: dropdown
    id: willing_to_pr
    attributes:
      label: "是否愿意提交 PR"
      description: 你是否愿意自己实现这个功能并提交 PR？
      options:
        - 是，我可以提交 PR
        - 否，希望维护者实现
        - 需要指导后可以尝试
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: "补充信息"
      description: 其他任何相关信息、截图或参考链接
    validations:
      required: false
